### ISSUE TITLE
Discuss name change

### ISSUE THREAD

**Issue by elisechant** [designsystemau/blog#11]
Should the design system name change from Australian Government Design System to GOLD Design System or another.

This might need an RFC.

**Comment by elisechant** [comment]
cc @dominikwilkowski

**Comment by dominikwilkowski** [comment]
My thoughts expressed here: https://twitter.com/wilkowskidom/status/1426350990446399490

**Comment by elisechant** [comment]
Closing because created an RFC in favour of changing https://github.com/designsystemau/RFCs/pull/8
